version: '3'
services:
  web-test:
    build: ./app
    image: sdpx/api
    ports:
      - 8082:5000
    restart: always
    environment:
      - DATABASE_NAME=db-test
      - DATABASE_PORT=3306
      - DATABASE_HOST=mydb-test
    
  mydb-test:
    image: sdpx/db
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=db-test
    volumes:
      - D:\Documents\01_Study_Files\SDPX\Docker_assignment\mysqldata-test:/var/lib/mysql
  # myadmin-test:
  #   image: phpmyadmin
  #   ports:
  #     - 9088:80
  #   environment:
  #     - PMA_HOST=mydb-test
  #   depends_on:
  #     - mydb-test

networks:
  database:

